years:
  min: 1959
  max: 2015 # choix dans le menu

statisticals:
  modelised: data/statisticals/modelised
  observed: data/statisticals/observed

gev_sta:
  modelised: data/gev/modelised
  observed: data/gev/observed

gev_non_sta:
  modelised: data/gev_non_sta/modelised
  observed: data/gev_non_sta/observed
