years:
  min: 1959
  max: 2020 # choix dans le menu
  rupture: 1985

statisticals:
  modelised: data/statisticals/modelised
  observed: data/statisticals/observed

gev:
  modelised: data/gev/modelised
  observed: data/gev/observed