echelles:
  - horaire

nc:
  path:
    inputdir: "data/raw/modelised" # précipitation en kg/m²/s

metadata:
  path:
    outputdir: "data/metadonnees/modelised"

spatial_filter:
  ne_directory: "data/external/naturalearth"

zarr:
  path:
    outputdir: "data/processed/modelised/zarr"
  overwrite: true  # Ecraser ou non les .zarr existants
  chunks:
    time: .inf  # on garde full time
    points: 100  # par 100 points
  compressor:
    blosc:
      cname: zstd
      clevel: 9
      shuffle: 1
  variables:
    pr:
      dtype: int16
      unit_conversion: 3600     # kg/m²/s → mm/h
      scale_factor: 10          # pour enregistrer pr * 10 en int16 (un chiffre après la virgule) : 1.25 deviendra 1.3
      fill_value: -9999

statistics:
  path:
    outputdir: "data/statisticals/modelised"
  overwrite: true  # ou false pour ne pas écraser les .parquet existants par défaut

log:
  directory: "logs/pipeline/modelised"  # dossier où sera écrit les fichiers .log