echelles:
  - horaire
  - quotidien

data:
  download: true # active ou non le téléchargement
  delete: false # supprime les fichiers temporaires

metadata:
  path:
    outputdir: "data/metadonnees/observed"

spatial_filter:
  ne_directory: "data/external/naturalearth"

zarr:
  path:
    outputdir: "data/processed/observed/zarr"
  overwrite: false 
  chunks:
    time: .inf  # on garde full time
    points: 100  # par 100 points
  compressor:
    blosc:
      cname: zstd
      clevel: 9
      shuffle: 1
  variables:
    pr:
      dtype: int16
      unit_conversion: 1        # en mm/h ou mm/j
      scale_factor: 10           # pour enregistrer pr * 10 en int16 (un chiffre après la virgule) : 1.25 deviendra 1.3
      fill_value: -9999

aggregate:
  enable: true


statistics:
  path:
    outputdir: "data/statisticals/observed"
  overwrite: true  # ou false pour ne pas écraser les .parquet existants par défaut

obs_vs_mod:
  path:
    outputdir: "data/obs_vs_mod"
  metadata_path:
    outputdir: "data/metadonnees/obs_vs_mod"
    
gev:
  path:
    outputdir: "data/gev/observed"
  break_year: 1985

log:
  directory: "logs/pipeline/observed"  # dossier où sera écrit les fichiers .log