echelles:
  - horaire
  - quotidienne

metadonnees:
  path:
    outputdir: "data/metadonnees"

nc:
  horaire:
    path:
      outputdir: "data/raw/observed/horaire" # précipitation mm/h
  quotidien:
    path:
      outputdir: "data/raw/observed/quotidien" # précipitation mm/j

spatial_filter:
  ne_directory: "data/external/naturalearth"

zarr:
  path:
    outputdir: "data/processed/observed/zarr"
  overwrite: true 
  chunks:
    time: .inf  # on garde full time
    points: 100  # par 100 points
  compressor:
    blosc:
      cname: zstd
      clevel: 9
      shuffle: 1
  variables:
    pr:
      dtype: int16
      unit_conversion: 1        # en mm/h ou mm/j
      scale_factor: 10          # pour enregistrer pr * 10 en int16 (un chiffre après la virgule) : 1.25 deviendra 1.3
      fill_value: -9999

log:
  directory: "logs/pipeline/observed"  # dossier où sera écrit les fichiers .log