nc:
  path:
    inputdir: "data/raw/modelised"

spatial_filter:
  ne_directory: "data/external/naturalearth"

zarr:
  path:
    outputdir: "data/processed/modelised/zarr"
  overwrite: false  # Ne pas écraser les .zarr existants par défaut
  chunks:
    time: .inf  # on garde full time
    points: 100  # par 100 points
  compressor:
    blosc:
      cname: zstd
      clevel: 9
      shuffle: 1
  variables:
    pr:
      dtype: int16
      scale_factor: 10  # pour enregistrer pr * 10 en int16 (un chiffre après la virgule) : 1.25 deviendra 1.3
      fill_value: -9999 # sentinelle des NaN
    lat:
      dtype: float32 # perte de précision de 10 m
    lon:
      dtype: float32 # perte de précision de 10 m

log:
  directory: "logs/pipeline"  # dossier où sera écrit les fichiers .log