name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Supprime juste ce qui est inutile mais garde /data/result/preanalysis
          rm -rf .git .github src data/raw data/external data/processed data/binaires

          # Le répertoire courant devient la racine
          git init
          git config user.email "ncsdecoopman@github.com"
          git config user.name "NCSdecoopman"
          git branch -M main
          git remote add hf https://ncsdecoopman:${HF_TOKEN}@huggingface.co/spaces/ncsdecoopman/extreme-precip-app.git
          git add .
          git commit -m "Deploy app to HF Space"
          git push hf main --force
