name: build-and-deploy-quarto

on:
  push:
    branches: [ data-pipeline ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: release
          tinytex: true

      - name: Render Quarto (fichiers ciblés)
        run: |
          # set -e
          # quarto render rapport/rapport.qmd
          # quarto render rapport/annexes.qmd
          # quarto render presentation/presentation.qmd

          mkdir -p _site
          # PDFs
          find rapport annexes presentation -type f -name '*.pdf' -exec cp --parents {} _site \;

          touch _site/.nojekyll

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
